server:
  port: 8080
  host: "localhost"

mysql:
  dsn: "user:password@tcp(mysql:3306)/macro_bi_cmp_528?parseTime=true"
  max_retries: 3
  retry_interval: "15s"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: "1h"

postgres:
  dsn: "postgresql://postgres:password@db:5432/reports_db?sslmode=disable"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: "1h"

rabbitmq:
  url: "amqp://guest:guest@rabbitmq:5672/"
  exchange: "audiences"
  queue: "audience.updates"

service:
  update_time: "0 1 * * *"  # Every day at 1 AM
  batch_size: 1000
  export_path: "./exports"

logger:
  level: "info"
  encoding: "json"
  output: "stdout"